export const CENSUSNAME: { [key: string]: number } = {
  "Civil Rights": 0,
  "Economy": 1,
  "Political Freedom": 2,
  "Population": 3,
  "Authoritarianism": 53,
  "Average Disposable Income": 85,
  "Average Income": 72,
  "Average Income of Poor": 73,
  "Average Income of Rich": 74,
  "Averageness": 67,
  "Black Market": 79,
  "Business Subsidization": 31,
  "Charmlessness": 64,
  "Cheerfulness": 40,
  "Compassion": 6,
  "Compliance": 42,
  "Corruption": 51,
  "Crime": 77,
  "Culture": 55,
  "Death Rate": 5,
  "Defense Forces": 46,
  "Eco-Friendliness": 7,
  "Economic Freedom": 48,
  "Economic Output": 76,
  "Employment": 56,
  "Environmental Beauty": 63,
  "Food Quality": 88,
  "Foreign Aid": 78,
  "Freedom From Taxation": 50,
  "Government Size": 27,
  "Health": 39,
  "Human Development Index": 68,
  "Ideological Radicality": 45,
  "Ignorance": 37,
  "Inclusiveness": 71,
  "Income Equality": 33,
  "Industry: Arms Manufacturing": 16,
  "Industry: Automobile Manufacturing": 10,
  "Industry: Basket Weaving": 12,
  "Industry: Beverage Sales": 18,
  "Industry: Book Publishing": 24,
  "Industry: Cheese Exports": 11,
  "Industry: Furniture Restoration": 22,
  "Industry: Gambling": 25,
  "Industry: Information Technology": 13,
  "Industry: Insurance": 21,
  "Industry: Mining": 20,
  "Industry: Pizza Delivery": 14,
  "Industry: Retail": 23,
  "Industry: Timber Woodchipping": 19,
  "Industry: Trout Fishing": 15,
  "Influence": 65,
  "Integrity": 52,
  "Intelligence": 36,
  "International Artwork": 86,
  "Law Enforcement": 30,
  "Lifespan": 44,
  "Niceness": 34,
  "Nudity": 9,
  "Obesity": 61,
  "Pacifism": 47,
  "Patriotism": 87,
  "Political Apathy": 38,
  "Primitiveness": 69,
  "Public Education": 75,
  "Public Healthcare": 29,
  "Public Transport": 57,
  "Recreational Drug Use": 60,
  "Religiousness": 32,
  "Residency": 80,
  "Rudeness": 35,
  "Safety": 43,
  "Scientific Advancement": 70,
  "Sector: Agriculture": 17,
  "Sector: Manufacturing": 26,
  "Secularism": 62,
  "Social Conservatism": 8,
  "Taxation": 49,
  "Tourism": 58,
  "Wealth Gaps": 4,
  "Weaponization": 59,
  "Weather": 41,
  "Welfare": 28,
  "World Assembly Endorsements": 66,
  "Youth Rebelliousness": 54,
}
